# Generated by Django 6.0 on 2025-12-06 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kelompok',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(help_text='Masukkan nama kelompok', max_length=200, verbose_name='Nama Kelompok')),
                ('tanggal_berdiri', models.DateField(help_text='Tanggal kelompok didirikan', verbose_name='Tanggal Berdiri')),
                ('jumlah_anggota', models.IntegerField(help_text='Jumlah anggota dalam kelompok', verbose_name='Jumlah Anggota')),
                ('luas_lahan', models.FloatField(help_text='Luas lahan yang dimiliki dalam hektar', verbose_name='Luas Lahan (Ha)')),
                ('frekuensi_bantuan', models.IntegerField(help_text='Jumlah bantuan yang pernah diterima', verbose_name='Frekuensi Bantuan')),
                ('sdm', models.IntegerField(help_text='Skor kualitas SDM (1-10)', verbose_name='Kualitas SDM')),
                ('unit_usaha', models.IntegerField(help_text='Skor unit usaha (1-10)', verbose_name='Unit Usaha')),
                ('kas', models.IntegerField(help_text='Skor kas kelompok (1-10)', verbose_name='Kas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Kelompok',
                'verbose_name_plural': 'Kelompok',
                'ordering': ['nama'],
            },
        ),
    ]
