# Generated by Django 6.0 on 2025-12-12 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuzzy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuzzyParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variabel', models.CharField(choices=[('usia', 'Usia'), ('frekuensi_bantuan', 'Frekuensi Bantuan'), ('luas_lahan', 'Luas Lahan'), ('jumlah_anggota', 'Jumlah Anggota'), ('sdm', 'SDM'), ('unit_usaha', 'Unit Usaha'), ('kas', 'Kas')], max_length=50, verbose_name='Variabel')),
                ('kategori', models.CharField(help_text='Contoh: baru, sedang, lama', max_length=50, verbose_name='Kategori')),
                ('tipe_fungsi', models.CharField(choices=[('bahu_kiri', 'Bahu Kiri (Left Shoulder)'), ('segitiga', 'Segitiga (Triangle)'), ('bahu_kanan', 'Bahu Kanan (Right Shoulder)')], max_length=20, verbose_name='Tipe Fungsi')),
                ('param_a', models.FloatField(help_text='Batas bawah atau titik awal', verbose_name='Parameter A')),
                ('param_b', models.FloatField(help_text='Titik tengah atau batas atas', verbose_name='Parameter B')),
                ('param_c', models.FloatField(blank=True, help_text='Batas atas (hanya untuk fungsi segitiga)', null=True, verbose_name='Parameter C')),
                ('keterangan', models.TextField(blank=True, help_text='Penjelasan tentang parameter ini', verbose_name='Keterangan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Parameter Fuzzy',
                'verbose_name_plural': 'Parameter Fuzzy',
                'ordering': ['variabel', 'kategori'],
                'unique_together': {('variabel', 'kategori')},
            },
        ),
    ]
